import type { QRPreset } from '../types/qr';

export const PRESETS: QRPreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Crisp black on pure white. Universal compatibility.',
    foreground: '#000000',
    background: '#FFFFFF',
    errorCorrection: 'M',
    margin: 3,
    tag: 'Standard',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Soft zinc dark tone with generous quiet zone.',
    foreground: '#18181B',
    background: '#FFFFFF',
    errorCorrection: 'M',
    margin: 4,
    tag: 'Clean',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Bright ice on deep slate navy with resilient error correction.',
    foreground: '#F8FAFC',
    background: '#0F172A',
    errorCorrection: 'H',
    margin: 3,
    tag: 'Dark',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Vibrant cobalt blue on crisp white.',
    foreground: '#1D4ED8',
    background: '#FFFFFF',
    errorCorrection: 'M',
    margin: 3,
    tag: 'Vibrant',
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Rich emerald green on fresh mint-white.',
    foreground: '#047857',
    background: '#F0FDF4',
    errorCorrection: 'M',
    margin: 3,
    tag: 'Natural',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Deep crimson rose on delicate warm background.',
    foreground: '#BE123C',
    background: '#FFF1F2',
    errorCorrection: 'M',
    margin: 3,
    tag: 'Warm',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Electric amber gold on obsidian black.',
    foreground: '#FACC15',
    background: '#18181B',
    errorCorrection: 'H',
    margin: 3,
    tag: 'Bold',
  },
];
